### ISSUE TITLE
京东物流对接参数问题

### ISSUE THREAD

**Issue by happyLiu97** [mr-xiaoyu/express-java-tools#1]
您好，大佬 我再用你封装好的代码时，那个京东的代码 我有点不太懂 就是 我在Jdlconfig配置了 但是别的地方获取不到  
期待你抽出空 帮我解答一下 万分感谢！！

**Comment by mr-xiaoyu** [comment]
要在哪里获取？

**Comment by mr-xiaoyu** [comment]
最好提供一下代码片段

**Comment by happyLiu97** [comment]
可以加你个微信什么的吗 我上班联系您




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mr-xiaoyu/express-java-tools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月31日(星期二) 晚上11:29
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [mr-xiaoyu/express-java-tools] 京东物流对接参数问题 (Issue #1)





 
要在哪里获取？

**Comment by happyLiu97** [comment]
public R receiveOrder(@RequestBody String json) throws ExpressErrorException, IOException {
        WaybillDTO waybillDTO = JSONObject.parseObject(json, WaybillDTO.class);
        ReceiveOrderInfoRequest request = ReceiveOrderInfoRequest.builder().build();
        request.setWaybillDTO(waybillDTO);
        ReceiveOrderInfoResponse response = jdlOrderService.receiveOrder(request);
        return R.ok().put("response",response);

这个是控制层， 请求之后 返回是url无效的问题 我不太清楚 是不是我少了什么参数 代码有点多 具体截哪里的

**Comment by happyLiu97** [comment]
您说的那个获取配置的 我写了一个工厂类 用于把配置类注册到容器里 
public class ConfigFactory implements FactoryBean<JdlConfig> {

    private static JdlConfig jdlConfig = null;

    @Override
    public JdlConfig getObject() throws Exception {
        if (jdlConfig == null) {
            synchronized (JdlConfig.class) {
                if (jdlConfig == null) {
                    jdlConfig = new JdlConfig();
                }
            }
        }
        return jdlConfig;
    }

    @Override
    public Class<?> getObjectType() {
        return JdlConfig.class;
    }

**Comment by happyLiu97** [comment]
就可以获取到配置信息了 那个请求路径是拼接的嘛  但是我不知道 我少了哪个参数或者 是哪里没有弄对 请求过去一直返回的都是 无效url

**Comment by happyLiu97** [comment]
现在参数调通了  
但是会报错 经过这个类的时候 会报错
 private void resultSuccess(BaseRequest request,String result) throws ExpressErrorException {
        JsonObject obj = JdlGsonBuilder.create().fromJson(result, JsonObject.class);
        if(!obj.has(request.getCodeField())){
            throw new ExpressErrorException(ExpressError.builder()
                    .errorCode("9999")
                    .errorMsg("状态码不存在")
                    .json(result)
                    .build());
        }
        Integer code = obj.get(request.getCodeField()).getAsInt();
        if(!request.getSuccessCode().equals(code)){
            throw new ExpressErrorException(ExpressError.builder()
                    .errorCode(String.valueOf(code))
                    .json(result)
                    .build());
        }
    }
我不太明白这个类是干嘛的

**Comment by mr-xiaoyu** [comment]
这个类是用来判断请求是否成功的

**Comment by mr-xiaoyu** [comment]
使用 JdlService 必须 setConfig ，因为要获取Token

**Comment by happyLiu97** [comment]
但是我的请求经过这里 报错 但是我请求是成功了的

**Comment by mr-xiaoyu** [comment]
请求的哪个接口？我试试

**Comment by happyLiu97** [comment]
下单接口

**Comment by happyLiu97** [comment]
receiveOrder

**Comment by happyLiu97** [comment]
"错误代码：104, 错误信息：null，原始报文：{\"deliveryId\

**Comment by mr-xiaoyu** [comment]
下单成功了，在wl.jdl.com 可以看见运单；但是接口抛异常是吧？异常信息可以提供一下吗

**Comment by happyLiu97** [comment]
要不我加您个微信您看怎么样

**Comment by mr-xiaoyu** [comment]
邮箱给我一下

**Comment by happyLiu97** [comment]
18243018809




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月2日(星期四) 下午4:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [mr-xiaoyu/express-java-tools] 京东物流对接参数问题 (Issue #1)





 
邮箱给我一下

**Comment by mr-xiaoyu** [comment]
加你了
